---
- name : provision web servers
  hosts: tag_server_role=web
  become: yes
    
  tasks:

  - name: install packages
    apt:
      name: 
        - software-properties-common
        - nginx
      update_cache: yes
