---
- hosts: default
  become: yes

  tasks:

  - name: install packages
    apt:
      name:
        - software-properties-common
        - nginx
        - redis
      state: present
      update_cache: yes

  - name: stop services
    service:
      name: "{{ item }}"
      state: stopped
    loop:
      - nginx
      - redis

  - name: touch file
    become_user: ubuntu
    file:
      path: "~/ubuntu1804_base_image"
      state: touch