---
- name : provision ansible control server
  hosts: tag_app_name=ansible:&tag_server_role=control
  gather_facts: no 

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_dir: ~/ansible/
    ansible_job: "cd {{ ansible_dir }} && ansible-playbook -i oci_inventory.py -e 'ansible_python_interpreter=/usr/bin/python3' tasks/*.yml"
    src_dir: ~/github/oci_ansible_modules/
    
  tasks:

  - name: update repositories cache
    become: yes
    apt:
      name: software-properties-common
      update_cache: yes

  - name: add ansible repo
    become: yes
    apt_repository:
      repo: ppa:ansible/ansible

  - name: install os packages
    become: yes
    package:
      name: 
        - ansible
        - python-pip
        - rsync
        - tree

  # - name: install python packages
  #   become: yes
  #   pip:
  #     name:
  #       - oci==2.1.1

  - name: install python packages
    become: yes
    shell: pip install oci

  - name: create directory to store ansible files
    file:
      path: "{{ ansible_dir }}"
      state: directory

  - name: upload creds files
    copy:
      src:  "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: 0400
    loop:
      - {src: '~/.ssh/id_rsa',          dest: '~/.ssh/'}
      - {src: '~/.oci/oci_api_key.pem', dest: '~/.oci/'}
      - {src: '~/.oci/config',          dest: '~/.oci/'}

  - name: rsync playbooks and other files
    synchronize:
      src:  "{{ item.src }}"
      dest: "{{ item.dest }}"
      rsync_opts:
        - "--exclude=*.retry"
        - "--exclude=ansible_control.yml"
    loop:
      - {src: "{{ src_dir }}ansible/playbooks/dynamic/",            dest: "{{ ansible_dir }}"}
      - {src: "{{ src_dir }}oci-ansible-modules/inventory-script/", dest: "{{ ansible_dir }}"}

  - name: set exec permissions on oci_inventory.py
    file:
      path: "{{ ansible_dir }}oci_inventory.py"
      mode: u+x

  - name: create ansible.cfg
    copy: 
      # content: "[defaults]\nhost_key_checking = False"
      src: "{{ src_dir }}ansible/ansible_control.cfg"
      dest: "{{ ansible_dir }}ansible.cfg"

  - name: cron for running ansible-playbook
    cron:
      name: 'ansible-playbook'
      minute: "*/5"
      job: "{{ ansible_job }}"
      state: present
