---
- name : provision web servers
  hosts: tag_server_role=web
  become: yes
    
  tasks:

  - name: install packages
    apt:
      name: 
        - software-properties-common
        - nginx

  - name: start services
    service: 
      name: "{{ item }}"
      enabled: yes
      state: started
    loop:
      - nginx

  - name: touch file
    become_user: ubuntu
    file:
      path: "~/web"
      state: touch