---
- name : provision worker servers
  hosts: tag_server_role=worker
  become: yes
  strategy: free 
    
  tasks:

  - name: install packages
    apt:
      name: 
        - software-properties-common
        - redis

  - name: start services
    service: 
      name: "{{ item }}"
      enabled: yes
      state: started
    loop:
      - redis

  - name: touch file
    become_user: ubuntu
    file:
      path: "~/worker"
      state: touch