---
- name : List summary of existing buckets in OCI object storage
  connection: local
  hosts: localhost

  vars_files:
    - secret.yml

  tasks:
    - name: List bucket facts
      oci_bucket_facts:
         namespace_name: "{{ namespace_name }}"
         compartment_id: "{{ compartment_id }}"
      register: result
    - name: Dump result
      debug: 
        msg: '{{result}}'